services:
  # ---------------- PostgreSQL ----------------
  postgres:
    image: postgres:15
    container_name: postgres_db
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - microservice-net
    restart: unless-stopped

  # ---------------- pgAdmin ----------------
  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin_ui
    restart: unless-stopped
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    ports:
      - "127.0.0.1:5050:80"
    depends_on:
      - postgres
    networks:
      - microservice-net
    volumes:
      - pgadmin_data:/var/lib/pgadmin

  # ---------------- MongoDB ----------------
  mongodb:
    image: mongo:6.0
    container_name: mongodb
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    networks:
      - microservice-net

  # ---------------- Mongo Express ----------------
  mongo-express:
    image: mongo-express:latest
    container_name: mongo_express
    restart: unless-stopped
    ports:
      - "127.0.0.1:5051:8081"
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      ME_CONFIG_MONGODB_ADMINPASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
      ME_CONFIG_MONGODB_SERVER: mongodb
      ME_CONFIG_BASICAUTH_USERNAME: ${ME_CONFIG_BASICAUTH_USERNAME}       # Web UI username
      ME_CONFIG_BASICAUTH_PASSWORD: ${ME_CONFIG_BASICAUTH_PASSWORD}
    depends_on:
      - mongodb
    networks:
      - microservice-net

  # ---------------- MailDev ----------------
  maildev:
    image: maildev/maildev
    container_name: maildev
    restart: unless-stopped
    ports:
      - "1080:1080"   # Web UI
      - "1025:1025"   # SMTP server
    networks:
      - microservice-net

# ---------------- Networks & Volumes ----------------
networks:
  microservice-net:
    driver: bridge

volumes:
  postgres_data:
  mongo_data:
  pgadmin_data:
