eureka:
  instance:
    hostname: localhost
  client:
      service-url:
        defaultZone: http://localhost:8762/eureka


#  This Below Part means if we have same properties in {service}.yml and in that service application.yml
#  so, it shouldn't Override the application.yml of that service
spring:
  cloud:
    config:
      override-system-properties: false