eureka:
  instance:
    hostname: localhost
  client:
      service-url:
        defaultZone: http://localhost:8762/eureka


#  This Below Part means if we have same properties in {service}.yml and in that service application.yml
#  so, it shouldn't Override the application.yml of that service
spring:
  cloud:
    config:
      override-system-properties: false


#  So, All Services can have this Zipkin Configuration
management:
  zipkin:
    tracing:
      connect-timeout: 5s
      read-timeout: 10s
      endpoint: http://localhost:9412/api/v2/spans      # Zepkin URL

  tracing:
    sampling:
      probability: 1.0      # DEV = Means all 100% request will be traced by zipkin
      # probability: 0.1     # PROD = Means 50% request will be traced by zipkin so, it not slows down service but still lets us analyze the flow
