server:
  port: 8092

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/order
    username: root
    password: root123
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    database: POSTGRESQL
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  flyway:
    baseline-on-migrate: true
    enabled: true
    baseline-description: "init"
    baseline-version: 0
    user: ${spring.datasource.username}
    password: ${spring.datasource.password}

  kafka:
    producer:
      bootstrap-servers: localhost:9092
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        # So, our consumer know what kind of object is coming after serializing
        spring.json.type.mapping: OrderConfirmationParams:com.ecommerce.Order.kafka.OrderConfirmationParams